project:
  type: website
  output-dir: docs
  preview: 
    port: 5240
    browser: true
    
execute:
  freeze: auto
  warning: false
  message: false

website:
  navbar:
    left:
      - href: index.qmd
        text: Report
      - href: reproducibility-supplement.qmd
        text: Reproducibility Supplement
  back-to-top-navigation: true
    
format:
  html:
    theme: litera
    toc: true
    toc-location: left    
    fontsize: 12pt
    page-layout: full
    margin-header: |
      ![](/www/logos/uhm-logo.png) <br><br>
      ![](/www/logos/nmbu-logo.png) <br><br>
      ![](/www/logos/uc-merced-logo.png) <br><br>
