project:
  type: website
  output-dir: docs
  preview: 
    port: 5240
    browser: true
    
execute:
  freeze: auto

website:
  title: |
    "Linking recreational visitation and environmental conditions to predict the 
    cost and welfare impacts of future environmental scenarios in the High Sierra <br>"
  navbar:
    left:
      - href: index.qmd
  back-to-top-navigation: true
    
format:
  html:
    theme: 
      - lumen
      - styles.scss
    toc: true
    fontsize: 15pt
    page-layout: full